ros_distro: "foxy"
base_image: "ubuntu:24.04"
service_name: "ros-foxy"
image_name: "ros-docker:foxy"
container_name: "ros-foxy-container"
dockerfile_path: "Dockerfile.foxy"
ros_package: "desktop"
system_packages:
  - dbus
  - dbus-x11
  - x11-apps

network_mode: "host"
x11: true
dbus: true
nvidia: true
