ros_distro: "humble"
base_image: "ubuntu:22.04"
service_name: "ros-humble"
image_name: "ros-docker:humble"
container_name: "ros-humble-container"
dockerfile_path: "Dockerfile.humble"
ros_package: "desktop"
system_packages:
  - dbus
  - dbus-x11
  - x11-apps

network_mode: "host"
x11: true
dbus: true
nvidia: true
