ros_distro: "foxy"
base_image: "ubuntu:24.04"
service_name: "ros-foxy"
image_name: "ros-docker:foxy"
container_name: "ros-foxy-container"
dockerfile_path: "Dockerfile.foxy"
ros_package: "desktop"
system_packages:
  - dbus
  - dbus-x11
  - x11-apps
  - xclip
  - xdotool
  - zsh
  - neovim
  - fd-find
  - ripgrep
  - tmux
  - git-lfs
  - openssh-server
volumes:
  - "~/Projects:/home/foxy/Projects:rw"
environment:
  TERM: xterm-256color

network_mode: "host"
x11: true
dbus: true
nvidia: true
